name: Higia_videoCall
description: MVP for Higia.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  agora_rtc_engine: ^1.0.8
  permission_handler: ^4.4.0+hotfix.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: gill
      fonts:
        - asset: assets/fonts/gillsans.ttf
    - family: gillBold
      fonts:
        - asset: assets/fonts/gillSans_bold.ttf
